services:
  open-webui:
    ports:
      - '3000:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - 'open-webui:/app/backend/data'
    environment:
      ENABLE_OPENAI_API: true
      OPENAI_API_BASE_URLS: "https://api.openai.com/v1"
      OPENAI_API_KEYS: "sk-XXXXXXX"

    container_name: open-webui
    restart: always
    image: 'ghcr.io/open-webui/open-webui:main'
volumes:
  open-webui:

